# Generated by Django 5.1.1 on 2025-01-17 23:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[V|E|J|P][0-9]{5,9}$', 'La cédula debe tener el formato V123456789.')], verbose_name='Cédula')),
                ('first_name', models.CharField(max_length=255, verbose_name='Primer Nombre')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Segundo Nombre')),
                ('last_name_1', models.CharField(max_length=255, verbose_name='Primer Apellido')),
                ('last_name_2', models.CharField(blank=True, max_length=255, verbose_name='Segundo Apellido')),
                ('personal_email', models.EmailField(max_length=254, verbose_name='Correo Personal')),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^(0414|0424|0412|0416|0426)[-][0-9]{7}$', 'El teléfono debe tener el formato 04XX-1234567')], verbose_name='Teléfono Movil')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante', to='gakusei.person')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Activo', 'Active'), ('Retirado', 'Retired')], default='Activo', max_length=10, verbose_name='Status')),
                ('personal_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='gakusei.person')),
                ('representante', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gakusei.representante')),
            ],
        ),
        migrations.CreateModel(
            name='Sensei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucional_email', models.EmailField(max_length=254, verbose_name='Correo Institucional')),
                ('EN_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='B1', max_length=2, verbose_name='Nivel de Inglés')),
                ('JP_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], default='N4', max_length=2, verbose_name='Nivel de Japonés')),
                ('status', models.CharField(choices=[('Activo', 'Active'), ('Retirado', 'Retired')], default='Activo', max_length=10, verbose_name='Status')),
                ('personal_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensei', to='gakusei.person')),
            ],
        ),
    ]
