# Generated by Django 5.1.1 on 2025-01-18 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gakusei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.TextField(verbose_name='Ubicación')),
                ('contacto', models.TextField(verbose_name='Formas de Contacto')),
                ('maps', models.URLField(blank=True, max_length=500, verbose_name='Google Maps')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('horas_semanales', models.PositiveSmallIntegerField(verbose_name='Horas (min) Semanales')),
                ('precio', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Activa', 'Active'), ('En Pausa', 'Paused'), ('Suspendida', 'Suspended'), ('Terminanda', 'Completed')], default='Activa', max_length=10)),
                ('sensei', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='gakusei.sensei')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='gakusei.curso')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='gakusei.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lu'), ('Martes', 'Ma'), ('Miercoles', 'Mi'), ('Jueves', 'Ju'), ('Viernes', 'Vi'), ('Sábado', 'Sa'), ('Domingo', 'Do')], max_length=10, verbose_name='Dia de la Semana')),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='gakusei.clase')),
            ],
        ),
    ]
