# Generated by Django 5.1.1 on 2025-01-18 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gakusei', '0002_curso_sede_clase_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Becas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descuento', models.PositiveSmallIntegerField()),
                ('tipo_descuento', models.CharField(choices=[('Porcentual', 'Porcentual'), ('Cardinal', 'Cardinal')], default='Porcentual', max_length=10, verbose_name='Tipo de Descuento')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Deshabilitado', 'Desabilitado')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MetodosPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=255, verbose_name='Método')),
                ('datos', models.TextField(verbose_name='Datos de Pago')),
                ('obs', models.TextField(verbose_name='Observaciones')),
            ],
        ),
        migrations.AlterField(
            model_name='clase',
            name='status',
            field=models.CharField(choices=[('Activa', 'Activo'), ('En Pausa', 'Pausado'), ('Suspendida', 'Suspendido'), ('Terminanda', 'Completado')], default='Activa', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado')], default='Activo', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sensei',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado')], default='Activo', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Becados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beca', to='gakusei.estudiante')),
                ('beca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becados', to='gakusei.becas')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.PositiveSmallIntegerField()),
                ('obs', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descuento', to='gakusei.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='DiaDeClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número de Clase')),
                ('fecha', models.DateField()),
                ('status', models.CharField(choices=[('Impartida', 'Impartida'), ('Suspendida', 'Suspendida'), ('Cancelada', 'Cancelada')], default='Impartida', max_length=10)),
                ('obs', models.TextField(blank=True, verbose_name='Observaciones')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_de_clase', to='gakusei.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gakusei.estudiante')),
                ('dia_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gakusei.diadeclase')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveSmallIntegerField()),
                ('referencia', models.CharField(max_length=255)),
                ('obs', models.TextField(verbose_name='Observaciones')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gakusei.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gakusei.estudiante')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gakusei.metodospagos')),
            ],
        ),
        migrations.CreateModel(
            name='Solvencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=10)),
                ('pagado', models.CharField(choices=[('Pagado', 'Pagado'), ('Abonado', 'Abonado'), ('Sin Pagar', 'Sin Pagar')], default='Sin Pagar', max_length=10)),
                ('abonado', models.PositiveSmallIntegerField()),
                ('obs', models.TextField(verbose_name='Observaciones')),
                ('comprobante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solvencias', to='gakusei.pagos')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvencias', to='gakusei.estudiante')),
            ],
        ),
    ]
